# Generated by Django 5.2 on 2025-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('project1_title', models.CharField(max_length=200)),
                ('project1_description', models.TextField()),
                ('project1_link', models.URLField(blank=True)),
                ('project2_title', models.CharField(blank=True, max_length=200)),
                ('project2_description', models.TextField(blank=True)),
                ('project2_link', models.URLField(blank=True)),
                ('skills', models.TextField(help_text='Comma-separated skills like: Python, Django, SQL')),
            ],
        ),
    ]
