# Generated by Django 5.2 on 2025-04-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='project1_description',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='project1_link',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='project1_title',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='project2_description',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='project2_link',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='project2_title',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='skills',
        ),
        migrations.CreateModel(
            name='ProjectDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.profiledb')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.profiledb')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(help_text='1-100 scale')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.profiledb')),
            ],
        ),
    ]
