# Generated by Django 5.2 on 2025-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_remove_profiledb_project1_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldb',
            name='proficiency',
            field=models.IntegerField(help_text='1-100% scale'),
        ),
    ]
