# Generated by Django 5.2 on 2025-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_profiledb_age_profiledb_role_alter_profiledb_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiledb',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
