# Generated by Django 5.2 on 2025-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_profiledb_mobile_profiledb_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='main_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
