# Generated by Django 5.2 on 2025-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_profiledb_main_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
