# Generated by Django 5.2 on 2025-04-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0008_techstackdb_delete_skilldb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstackdb',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='tech_icons/'),
        ),
    ]
