# Generated by Django 5.2 on 2025-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0009_alter_techstackdb_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationdb',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationdb',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationdb',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
