# Generated by Django 5.2 on 2025-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0010_alter_qualificationdb_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationdb',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
