# Generated by Django 5.2 on 2025-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0011_qualificationdb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationdb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
