# Generated by Django 5.2 on 2025-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0012_alter_qualificationdb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationdb',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
