# Generated by Django 5.2 on 2025-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0013_qualificationdb_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationdb',
            name='summary',
        ),
        migrations.AddField(
            model_name='profiledb',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
