# Generated by Django 5.2 on 2025-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0016_alter_experiencedb_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdb',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectdb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
